pull_request_rules:
  - name: automatic merge when CI passes
    conditions:
      - "status-success=ci/circleci: build"
      - status-success=pyup.io/safety-ci
      - base=master
    actions:
      merge:
        method: merge
