name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'No activity in this issue for a while, labeling as stale'
        stale-pr-message: 'This pull request has been open for too long, closing automatically'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
